{
  Owner:{
     name:"Nicola Hill",
     id:"3430088000000176021",
     email:"nicola.hill@johnhill.com.au"
  },
  Build_Area_sqm:2500,
  $currency_symbol:"AU$",
  Suburb:"Rhodes",
  "Latitude":"-33.8247535",
  "Admin_Fields":true,
  "Office_area_sqm":1500,
  "Unit":null,
  "Last_Activity_Time":"2020-06-06T08:08:44+10:00",
  Autoupdate:true,
  Recent_Note:null,
  Water_Rates:null,
  Detailed_View:true,
  Council_Rates:null,
  $state:"save",
  "$process_flow":false,
  "Deal_Name":"2 Leeds Street, Rhodes",
  "Currency":"AUD",
  "Stage":"Current Listing",
  "Strata_Plan":null,
  "Street":"Leeds Street",
  "Sale_Price":1250000,
  "id":"3430088000003363001",
  "$approved":true,
  "Street_No":"2",
  "$approval":{
     "delegate":false,
     "approve":false,
     "reject":false,
     "resubmit":false
  },
  "Total_Income":null,
  "Building_Complex_Strata_Title_Not_Applicable":"Torrens",
  "Retail_sqm":null,
  "Created_Time":"2020-06-02T10:21:18+10:00",
  "Source_ID":null,
  "$editable":true,
  "Grade":null,
  "Longitude":"151.0922418",
  "Postcode":"2138",
  "Land_Tax":null,
  "Add_Note":null,
  "Lot":null,
  "State":"NSW",
  "Property_Contacts":null,
  "User":null,
  "$review_process":{
     "approve":false,
     "reject":false,
     "resubmit":false
  },
  "Outgoings_Basis":null,
  "Council":"City of Canada Bay Council",
  "Showroom_sqm":null,
  "$review":null,
  "Lead_Conversion_Time":null,
  "Overall_Sales_Duration":null,
  "Listing_No":"316002315",
  "Property_Type_Portals":[
     "Commercial",
     "Industrial"
  ],
  "Known_As":null,
  "Modified_Time":"2020-06-03T12:11:08+10:00",
  "Prop_Zoning":"Zone IN1 \u2013 General Industrial",
  "Sale_Type":[

  ],
  "Land_Area_sqm":1769,
  "Car_Spaces":3,
  "$orchestration":false,
  "Sales_Cycle_Duration":null,
  "Property_Owners":null,
  "Sale_Date":"1984-06-07",
  "Total_Outgoings":250000,
  "Reverse_Geocoded_Address":"2 Leeds St, Rhodes NSW 2138, Australia",
  "$in_merge":false,
  "Insurance":null,
  "Warehouse_sqm":1000,
  "Tag":[

  ],
  "Level_Suite":null,
  "Property_Category_Mailing":[
     "Gym/fitness",
     "Medical/dental",
     "Automotive Service",
     "Development",
     "Office",
     "Warehouse",
     "Bulky Goods/Showroom"
  ],
  "Managed":null,
  "Other":null
}